[config]
reload_apps = true

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-template.lua"
output_path = "~/.config/hypr/colors.lua"
post_hook = "hyprctl reload"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-template.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -USR2 waybar"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-template.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "kill -SIGUSR1 $(pgrep kitty)"
