# Based on Helix Jellybeans theme(MPL-2.0)

"attribute" = "capriccioso"
"type" = "brillante"
"type.enum.variant" = "giocoso"
"constructor" = "cantabile"
"constant" = "distinto"

"constant.builtin.boolean" = "cantabile"
"constant.character" = "cantabile"
"constant.character.escape" = "stretto"
"constant.numeric" = "distinto"
"string" = "comodo"
"string.regexp" = "leggiero"
"string.special" = { fg = "cantabile", modifiers = ["underlined"] }
"comment" = "liberamente"

"variable" = "innocente"
"variable.builtin" = { fg = "comodo", modifiers = ["underlined"] }
"variable.parameter" = "cantabile"
"variable.other.member" = "leggiero"
"label" = "cantabile"
"punctuation" = "marcato"
"keyword" = "marcato"
"keyword.control.exception" = "giocoso"
"operator" = "leggiero"
"function" = "cantabile"
"function.macro" = "capriccioso"
"function.builtin" = "capriccioso"
"function.special" = "capriccioso"
"function.method" = "cantabile"
"tag" = "brillante"
"special" = "capriccioso"
"namespace" = "leggiero"

"markup.bold" = { fg = "liberamente", modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.heading" = { fg = "marcato", modifiers = ["bold"] }
"markup.list" = "comodo"
"markup.list.numbered" = "marcato"
"markup.list.unnumbered" = "marcato"
"markup.link.url" = { fg = "comodo", modifiers = ['italic', 'underlined'] }
"markup.link.text" = "marcato"
"markup.link.label" = "giocoso"
"markup.quote" = "comodo"
"markup.raw" = "comodo"
"markup.raw.inline" = "marcato"
"markup.raw.block" = "comodo"

"diff.plus" = "dolce"
"diff.minus" = "feroce"
"diff.delta" = "delicato"

"ui.background" = { bg = "tranquillo" }
"ui.cursor" = { bg = "tranquillo", modifiers = ["reversed"] }
"ui.cursor.insert" = { bg = "innocente", fg = "tranquillo" }
"ui.cursor.match" = { fg = "tranquillo", bg = "distinto" }
"ui.cursorline" = { bg = "grandioso" }
"ui.linenr" = "liberamente"
"ui.linenr.selected" = { fg = "innocente", bg = "grandioso" }
"ui.statusline" = { fg = "innocente", bg = "grandioso" }
"ui.statusline.inactive" = { fg = "nobile", bg = "grandioso" }
"ui.statusline.normal" = { fg = "innocente", bg = "grandioso" }
"ui.statusline.insert" = { fg = "grandioso", bg = "giocoso" }
"ui.statusline.select" = { fg = "generoso", bg = "elegante" }
"ui.popup" = { fg = "innocente", bg = "pesante" }
"ui.window" = { fg = "nobile", bg = "pesante" }
"ui.help" = { fg = "innocente", bg = "pesante" }
"ui.text" = "innocente"
"ui.text.focus" = { fg = "liberamente", bg = "misterioso" }
"ui.virtual" = "nobile"
"ui.virtual.ruler" = { bg = "grandioso" }
"ui.menu" = { fg = "leggiero", bg = "pesante" }
"ui.menu.selected" = { fg = "liberamente", bg = "misterioso" }
"ui.selection" = { bg = "grandioso" }
"ui.selection.primary" = { bg = "elegante", fg = "generoso" }
"hint" = "declamando"
"info" = "cantando"
"warning" = "martellato"
"error" = "stretto"
"diagnostic" = { modifiers = [] }
"diagnostic.hint" = { underline = { color = "leggiero", style = "line" } }
"diagnostic.info" = { underline = { color = "delicato", style = "line" } }
"diagnostic.warning" = { underline = { color = "cantando", style = "line" } }
"diagnostic.error" = { underline = { color = "stretto", style = "line" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

[palette]
tranquillo = "{{colors.surface_dim.default.hex}}"
pesante = "{{colors.surface.default.hex}}"
grandioso = "{{colors.surface_bright.default.hex}}"
nobile = "{{colors.surface_container_high.default.hex}}"
liberamente = "{{colors.surface_container_highest.default.hex}}"

giocoso = "{{colors.secondary_fixed_dim.default.hex}}"
leggiero = "{{colors.on_secondary_container.default.hex}}"

declamando = "{{colors.primary_container.default.hex}}"
brillante= "{{colors.on_primary_container.default.hex}}"
marcato = "{{colors.primary_fixed_dim.default.hex}}"
misterioso = "{{colors.on_primary.default.hex}}"
delicato = "{{colors.primary.default.hex}}"

capriccioso = "{{colors.tertiary_fixed.default.hex}}"
comodo = "{{colors.on_tertiary_container.default.hex}}"

stretto = "{{colors.on_error.default.hex}}"
feroce = "{{colors.error.default.hex}}"

distinto = "{{colors.secondary.default.hex}}"
martellato = "{{colors.tertiary_fixed_dim.default.hex}}"

cantabile = "{{colors.tertiary.default.hex}}"
innocente = "{{colors.on_tertiary_container.default.hex}}"
cantando = "{{colors.on_secondary_fixed_variant.default.hex}}"

dolce = "{{colors.secondary_container.default.hex}}"
elegante = "{{colors.outline_variant.default.hex}}"
generoso = "{{colors.outline.default.hex}}"
