[palette]
background = "{{colors.surface.default.hex}}"
container_background = "{{colors.surface_container.default.hex}}"
container_text_color = "{{colors.on_surface.default.hex}}"


"attribute" = "{{colors.tertiary.default.hex}}"
"keyword" = {fg = "{{colors.primary.default.hex}}", modifiers = ["bold"]}
"keyword.directive" = "{{colors.secondary.default.hex}}"
"namespace" = "{{colors.secondary.default.hex}}"
"punct" = "{{colors.on_surface_variant.default.hex}}"
"string" = "{{colors.tertiary.default.hex}}"
"type" = "{{colors.secondary.default.hex}}"
"variable" = "{{colors.on_surface.default.hex}}"
"variable.builtin" = "{{colors.secondary.default.hex}}"
"variable.other.member" = "{{colors.primary.default.hex}}"
"constant" = "{{colors.tertiary.default.hex}}"
"comment" = {fg = "{{colors.outline.default.hex}}", modifiers = ["italic"]}
"markup.heading" = {fg = "{{colors.primary.default.hex}}", modifiers = ["bold"]}
"markup.bold" = {modifiers = ["bold"]}
"markup.italic" = {modifiers = ["italic"]}
"markup.link.url" = {fg = "{{colors.primary.default.hex}}", modifiers = ["underline"]}


"ui.background" = {bg = "background"}
"ui.background.separator" = {fg = "{{colors.outline.default.hex}}"}
"ui.cursor" = {bg = "background", fg = "{{colors.primary.default.hex}}"}
"ui.cursor.normal" = {bg = "background", fg = "{{colors.primary.default.hex}}"}
"ui.cursor.insert" = {bg = "background", fg = "{{colors.secondary.default.hex}}"}
"ui.cursor.select" = {bg = "background", fg = "{{colors.tertiary.default.hex}}"}
"ui.cursorline.primary" = {bg = "{{colors.surface_container_high.default.hex}}"}
"ui.statusline" = {bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}"}
"ui.statusline.normal" = {bg = "{{colors.primary.default.hex}}", fg = "background"}
"ui.statusline.insert" = {bg = "{{colors.secondary.default.hex}}", fg = "background"}
"ui.statusline.select" = {bg = "{{colors.tertiary.default.hex}}", fg = "background"}
"ui.popup" = {bg = "container_background", fg = "container_text_color"}
"ui.window" = {fg = "{{colors.outline_variant.default.hex}}"}
"ui.help" = {bg = "container_background", fg = "container_text_color"}
"ui.text" = {fg = "container_text_color"}
"ui.text.focus" = {fg = "{{colors.primary.default.hex}}"}
"ui.selection" = {bg = "{{colors.surface_container_highest.default.hex}}"}
