$primary = rgba({{colors.primary.default.hex_stripped}}ff)
$on_primary = rgba({{colors.on_primary.default.hex_stripped}})
$surface = rgba({{colors.surface.default.hex_stripped}})
$outline = rgba({{colors.outline.default.hex_stripped}})
$outline_variant = rgba({{colors.outline_variant.default.hex_stripped}})
