[[language]]
name = "c"
scope = "source.c"
file-types = ["c", "h"]
language-servers = ["clangd"]

[language-server.clangd]
command = "clangd"
args = ["--header-insertion=never", "--fallback-style=none"]

[[language]]
name = "python"
scope = "source.python"
file-types = ["py"]
language-servers = ["ruff"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "haskell"
scope = "source.haskell"
file-types = ["hs"]
language-servers = ["haskell-language-server"]

[[language-server.haskell-language-server]]
command = "/home/user/.ghcup/bin/haskell-language-server-wrapper-2.14.0.0"
args = ["--lsp"]

[[language]]
name = "julia"
scope = "source.julia"
file-types = ["jl"]
language-servers = ["julia-lsp"]

[[language]]
name = "latex"
scope = "source.tex"
injection-regex = "tex"
file-types = ["tex", "bib"]
roots = [".git", "Latexmkfile", "texlabroot"]
language-servers = [ "texlab" ]

[language-server.texlab]
command = "texlab"

[language-server.texlab.config.texlab]
build.onSave = true
build.executable = "latexmk"
build.args = ["-pdflua", "-interaction=nonstopmode", "-synctex=1", "%f"]
forwardSearch.executable = "zathura"
forwardSearch.args = ["--synctex-forward", "%l:%c:%f", "%p"]
