exec-once = waybar
exec-once = swww
exec-once = mako
exec-once = systemctl --user start hyprpolkitagent

$wallpapers_dir = $HOME/dotfiles/wallpapers
$default_wallpaper = $wallpapers_dir/adipocere.png
exec-once = swww-daemon
exec-once = swww img "$default_wallpaper" && matugen image "$default_wallpaper"
