background {
	path = /tmp/current-wallpaper
	blur_passes = 3
	blur_size = 6
}

input-field {
	size = 100, 25
	outline_thickness = 2
	dots_size = 0.4
	dots_center = true
	position = 0, -20
	halign = center
	valign = center
	hide_input = false
	inner_color = rgb(FFFFFF)
	font_color = rgb(10,10,10)
}

label {
	text = cmd[update:1000] echo "$TIME"
	font_size = 100
	font_family = JuliaMono Nerd Font
	position = 0, 150
	halign = center
	valign = center
	shadow_size = 16
	shadow_passes = 4
	color = rgb(FFFFFF)
}
