misc {
	vfr = true
	vrr = 1

	disable_hyprland_logo = true
	disable_splash_rendering = true
	force_default_wallpaper = 0

	mouse_move_enables_dpms = true
	key_press_enables_dpms = true
	focus_on_activate = true

	middle_click_paste = false
	allow_m4_middle_click = false

	initial_workspace_tracking = 1
}
