$terminal = kitty
$filemanager = dolphin
$browser = firefox

$menu = ~/dotfiles/custom-script/app-launcher.sh
$emoji = ~/dotfiles/custom-script/emoji.sh
$clipboard = ~/dotfiles/custom-script/clipboard.sh
$wallpaper_launcher = ~/dotfiles/custom-script/wallpaper.sh
