foreground #f0dede
background #1a1111
selection_foreground #ffdad9
selection_background #5d3f3f

cursor #ffb3b3
cursor_text_color #561d21

url_color #ffb3b3

active_border_color #ffb3b3
inactive_border_color #524343
bell_border_color #ffb4ab

active_tab_foreground #561d21
active_tab_background #ffb3b3
inactive_tab_foreground #d7c1c1
incative_tab_background #271d1d
tab_bar_background #1a1111

color0 #000000
color8 #7F7F7F

color1 #CD0000
color9 #FF0000

color2 #00CD00
color10 #00FF00

color3 #CDCD00
color11 #FFFF00

color4 #0000EE
color12 #5C5CFF

color5 #CD00CD
color13 #FF00FF

color6 #00CDCD
color14 #00FFFF

color7 #E5E5E5
color15 #FFFFFF
