foreground #dee4e4
background #0e1415
selection_foreground #cce7eb
selection_background #324b4e

cursor #81d4dd
cursor_text_color #00363b

url_color #81d4dd

active_border_color #81d4dd
inactive_border_color #3f484a
bell_border_color #ffb4ab

active_tab_foreground #00363b
active_tab_background #81d4dd
inactive_tab_foreground #bec8c9
incative_tab_background #1a2121
tab_bar_background #0e1415

color0 #000000
color8 #7F7F7F

color1 #CD0000
color9 #FF0000

color2 #00CD00
color10 #00FF00

color3 #CDCD00
color11 #FFFF00

color4 #0000EE
color12 #5C5CFF

color5 #CD00CD
color13 #FF00FF

color6 #00CDCD
color14 #00FFFF

color7 #E5E5E5
color15 #FFFFFF
