foreground #eae1d4
background #16130b
selection_foreground #f2e1bb
selection_background #50462a

cursor #e3c36c
cursor_text_color #3d2f00

url_color #e3c36c

active_border_color #e3c36c
inactive_border_color #4c4639
bell_border_color #ffb4ab

active_tab_foreground #3d2f00
active_tab_background #e3c36c
inactive_tab_foreground #cfc5b4
incative_tab_background #231f17
tab_bar_background #16130b

color0 #000000
color8 #7F7F7F

color1 #CD0000
color9 #FF0000

color2 #00CD00
color10 #00FF00

color3 #CDCD00
color11 #FFFF00

color4 #0000EE
color12 #5C5CFF

color5 #CD00CD
color13 #FF00FF

color6 #00CDCD
color14 #00FFFF

color7 #E5E5E5
color15 #FFFFFF
